server:
  port: 8080
  
spring:
  application:
    name: zuul

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/ 



# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


zuul: 
  ignoredServices: '*'
  routes:
    userService:
      path: /userService/**
      serviceId: userService
        
  prefix: /api   
  host:
    socket-timeout-millis: 60000
  

    
 